-- Landing Page Templates for the visual builder
-- Built-in templates are flagged is_public=1; user-created ones is_public=0

CREATE TABLE IF NOT EXISTS landing_page_templates (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  category ENUM('sweepstakes','vsl','ecommerce','crypto','dating','gaming','finance','leadgen','custom') NOT NULL DEFAULT 'custom',
  description TEXT,
  html_content LONGTEXT NOT NULL,
  fields JSON DEFAULT NULL,
  ctr_score DECIMAL(5,2) DEFAULT 0,
  is_public TINYINT(1) DEFAULT 0,
  user_id INT UNSIGNED DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_category (category),
  INDEX idx_is_public (is_public),
  INDEX idx_user_id (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Seed built-in templates
INSERT INTO landing_page_templates (name, category, description, html_content, fields, ctr_score, is_public) VALUES

-- 1. Sweepstakes
('iPhone Giveaway', 'sweepstakes', 'High-converting sweepstakes LP with countdown timer', '<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>*{margin:0;padding:0;box-sizing:border-box}body{font-family:system-ui,-apple-system,sans-serif;background:{{bg_color||#0a0a0a}};color:#fff;min-height:100vh;display:flex;flex-direction:column;align-items:center;justify-content:center;padding:20px}.badge{background:linear-gradient(135deg,{{accent_color||#6366f1}},{{accent2_color||#ec4899}});color:#fff;padding:6px 20px;border-radius:30px;font-size:12px;font-weight:700;letter-spacing:1px;margin-bottom:20px;text-transform:uppercase}h1{font-size:clamp(28px,5vw,48px);font-weight:800;text-align:center;margin-bottom:12px;line-height:1.2}h1 span{background:linear-gradient(135deg,{{accent_color||#6366f1}},{{accent2_color||#ec4899}});-webkit-background-clip:text;-webkit-text-fill-color:transparent}.timer{display:flex;gap:12px;margin:24px 0}.timer div{background:rgba(255,255,255,.08);border:1px solid rgba(255,255,255,.1);border-radius:12px;padding:12px 16px;min-width:70px;text-align:center}.timer .num{font-size:28px;font-weight:800;color:{{accent_color||#6366f1}}}.timer .lbl{font-size:10px;color:#94a3b8;margin-top:4px}p.sub{color:#94a3b8;text-align:center;max-width:460px;line-height:1.6;margin-bottom:28px}.cta{background:linear-gradient(135deg,{{accent_color||#6366f1}},{{accent2_color||#ec4899}});color:#fff;border:none;padding:16px 48px;font-size:17px;font-weight:700;border-radius:14px;cursor:pointer;box-shadow:0 8px 32px rgba(99,102,241,.4);transition:transform .2s}.cta:hover{transform:translateY(-2px) scale(1.03)}.social{text-align:center;margin-top:16px;font-size:12px;color:#64748b}</style></head><body><div class="badge">🏆 {{badge_text||LIMITED OFFER}}</div><h1>{{headline||Win a Brand New}}<br><span>{{headline2||iPhone 16 Pro}}</span></h1><div class="timer"><div><div class="num" id="h">02</div><div class="lbl">HOURS</div></div><div><div class="num" id="m">47</div><div class="lbl">MINS</div></div><div><div class="num" id="s">33</div><div class="lbl">SECS</div></div></div><p class="sub">{{description||Enter your details below for a chance to win. No purchase necessary. Limited time only!}}</p><button class="cta" onclick="window.open(\"{{offer_url||#}}\",\"_blank\")">{{cta_text||CLAIM YOUR PRIZE}}</button><p class="social">{{footer_text||Join 50,000+ participants worldwide}}</p><script>let s=9933;setInterval(()=>{s=Math.max(0,s-1);const h=Math.floor(s/3600),m=Math.floor(s%3600/60);document.getElementById(\"h\").textContent=String(h).padStart(2,\"0\");document.getElementById(\"m\").textContent=String(m).padStart(2,\"0\");document.getElementById(\"s\").textContent=String(s%60).padStart(2,\"0\")},1000)</script></body></html>',
  '[{"key":"headline","label":"Main Headline","type":"text","default":"Win a Brand New"},{"key":"headline2","label":"Highlight Text","type":"text","default":"iPhone 16 Pro"},{"key":"badge_text","label":"Badge","type":"text","default":"LIMITED OFFER"},{"key":"description","label":"Description","type":"textarea","default":"Enter your details below for a chance to win. No purchase necessary. Limited time only!"},{"key":"cta_text","label":"Button Text","type":"text","default":"CLAIM YOUR PRIZE"},{"key":"offer_url","label":"Offer URL","type":"text","required":true},{"key":"bg_color","label":"Background","type":"color","default":"#0a0a0a"},{"key":"accent_color","label":"Accent","type":"color","default":"#6366f1"},{"key":"accent2_color","label":"Accent 2","type":"color","default":"#ec4899"},{"key":"footer_text","label":"Footer","type":"text","default":"Join 50,000+ participants worldwide"}]',
  4.2, 1),

-- 2. VSL
('Video Sales Letter', 'vsl', 'Classic VSL page with embedded video and order button', '<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>*{margin:0;padding:0;box-sizing:border-box}body{font-family:system-ui,-apple-system,sans-serif;background:{{bg_color||#111}};color:#eee;min-height:100vh;display:flex;flex-direction:column;align-items:center;padding:40px 20px}h1{font-size:clamp(24px,4vw,40px);font-weight:800;text-align:center;max-width:700px;line-height:1.3;margin-bottom:8px}.sub{color:#94a3b8;text-align:center;max-width:520px;margin-bottom:28px;line-height:1.6}.vid{width:100%;max-width:720px;aspect-ratio:16/9;border-radius:16px;overflow:hidden;border:2px solid rgba(255,255,255,.08);background:#000;margin-bottom:32px}.vid iframe{width:100%;height:100%;border:0}.cta{background:{{accent_color||#ef4444}};color:#fff;border:none;padding:18px 56px;font-size:18px;font-weight:700;border-radius:12px;cursor:pointer;box-shadow:0 8px 32px rgba(239,68,68,.4);transition:transform .2s;animation:pulse 2s infinite}@keyframes pulse{0%,100%{box-shadow:0 0 0 0 rgba(239,68,68,.4)}50%{box-shadow:0 0 0 12px rgba(239,68,68,0)}}.cta:hover{transform:scale(1.05)}.guarantee{margin-top:20px;color:#64748b;font-size:12px;display:flex;align-items:center;gap:6px}</style></head><body><h1>{{headline||The Secret That Changed Everything}}</h1><p class="sub">{{description||Watch this short video to discover the breakthrough method thousands are using right now.}}</p><div class="vid"><iframe src="{{video_url||about:blank}}" allowfullscreen></iframe></div><button class="cta" onclick="window.open(\"{{offer_url||#}}\",\"_blank\")">{{cta_text||YES — I WANT ACCESS}}</button><p class="guarantee">🛡️ {{guarantee||60-Day Money-Back Guarantee. Zero Risk.}}</p></body></html>',
  '[{"key":"headline","label":"Headline","type":"text","default":"The Secret That Changed Everything"},{"key":"description","label":"Subheadline","type":"textarea","default":"Watch this short video to discover the breakthrough method thousands are using right now."},{"key":"video_url","label":"Video Embed URL","type":"text","required":true},{"key":"cta_text","label":"Button Text","type":"text","default":"YES — I WANT ACCESS"},{"key":"offer_url","label":"Offer URL","type":"text","required":true},{"key":"bg_color","label":"Background","type":"color","default":"#111111"},{"key":"accent_color","label":"CTA Color","type":"color","default":"#ef4444"},{"key":"guarantee","label":"Guarantee Text","type":"text","default":"60-Day Money-Back Guarantee. Zero Risk."}]',
  3.8, 1),

-- 3. E-Commerce
('Product Showcase', 'ecommerce', 'Clean product landing page with price and buy button', '<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>*{margin:0;padding:0;box-sizing:border-box}body{font-family:system-ui,-apple-system,sans-serif;background:{{bg_color||#f8fafc}};color:#1e293b;min-height:100vh}.top{text-align:center;padding:60px 20px 40px;max-width:800px;margin:0 auto}h1{font-size:clamp(28px,5vw,44px);font-weight:800;line-height:1.2;margin-bottom:8px}h1 em{font-style:normal;color:{{accent_color||#6366f1}}}.sub{color:#64748b;font-size:16px;margin-bottom:32px}.img-wrap{max-width:600px;margin:0 auto 32px;border-radius:20px;overflow:hidden;box-shadow:0 20px 60px rgba(0,0,0,.08)}.img-wrap img{width:100%;display:block}.price-box{text-align:center;margin-bottom:28px}.price-box .old{color:#94a3b8;text-decoration:line-through;font-size:18px}.price-box .now{font-size:36px;font-weight:800;color:{{accent_color||#6366f1}}}.features{display:grid;grid-template-columns:repeat(auto-fit,minmax(200px,1fr));gap:16px;max-width:600px;margin:0 auto 36px;padding:0 20px}.features div{background:#fff;border:1px solid #e2e8f0;border-radius:12px;padding:16px;text-align:center;font-size:14px}.features .icon{font-size:24px;margin-bottom:6px}.cta{display:block;max-width:400px;margin:0 auto 16px;background:{{accent_color||#6366f1}};color:#fff;border:none;padding:18px;font-size:17px;font-weight:700;border-radius:14px;cursor:pointer;text-align:center;text-decoration:none;box-shadow:0 8px 24px rgba(99,102,241,.3)}.trust{text-align:center;color:#94a3b8;font-size:12px;margin-bottom:40px}</style></head><body><div class="top"><h1>{{headline||The}} <em>{{headline2||Perfect Product}}</em></h1><p class="sub">{{description||Everything you need, delivered to your door in 2 days.}}</p></div><div class="img-wrap"><img src="{{product_image||https://placehold.co/600x400/6366f1/fff?text=Product}}"></div><div class="price-box"><div class="old">{{old_price||$199.00}}</div><div class="now">{{price||$49.00}}</div></div><div class="features"><div><div class="icon">⚡</div>Fast Shipping</div><div><div class="icon">🛡️</div>1 Year Warranty</div><div><div class="icon">↩️</div>30-Day Returns</div></div><a class="cta" href="{{offer_url||#}}">{{cta_text||BUY NOW — SAVE 75%}}</a><p class="trust">{{footer_text||Trusted by 100,000+ customers}}</p></body></html>',
  '[{"key":"headline","label":"Headline","type":"text","default":"The"},{"key":"headline2","label":"Highlight","type":"text","default":"Perfect Product"},{"key":"description","label":"Description","type":"textarea","default":"Everything you need, delivered to your door in 2 days."},{"key":"product_image","label":"Product Image URL","type":"text","default":"https://placehold.co/600x400/6366f1/fff?text=Product"},{"key":"price","label":"Price","type":"text","default":"$49.00"},{"key":"old_price","label":"Old Price","type":"text","default":"$199.00"},{"key":"cta_text","label":"Button Text","type":"text","default":"BUY NOW — SAVE 75%"},{"key":"offer_url","label":"Offer URL","type":"text","required":true},{"key":"bg_color","label":"Background","type":"color","default":"#f8fafc"},{"key":"accent_color","label":"Accent","type":"color","default":"#6366f1"},{"key":"footer_text","label":"Footer","type":"text","default":"Trusted by 100,000+ customers"}]',
  4.5, 1),

-- 4. Crypto
('Crypto Presale', 'crypto', 'Urgent crypto presale with live counter and wallet connect', '<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>*{margin:0;padding:0;box-sizing:border-box}body{font-family:system-ui,sans-serif;background:linear-gradient(135deg,{{bg_color||#0f0524}},#1a0a3e);color:#fff;min-height:100vh;display:flex;flex-direction:column;align-items:center;justify-content:center;padding:40px 20px}.badge{background:rgba(255,255,255,.06);border:1px solid rgba(255,255,255,.1);padding:6px 18px;border-radius:30px;font-size:12px;margin-bottom:20px;display:flex;align-items:center;gap:8px}.badge .dot{width:8px;height:8px;border-radius:50%;background:#22c55e;animation:blink 1.5s infinite}@keyframes blink{0%,100%{opacity:1}50%{opacity:.3}}h1{font-size:clamp(30px,5vw,52px);font-weight:800;text-align:center;line-height:1.15;margin-bottom:16px}h1 span{background:linear-gradient(135deg,{{accent_color||#f59e0b}},#f97316);-webkit-background-clip:text;-webkit-text-fill-color:transparent}.stats{display:flex;gap:32px;margin:24px 0;flex-wrap:wrap;justify-content:center}.stats div{text-align:center}.stats .val{font-size:28px;font-weight:800;color:{{accent_color||#f59e0b}}}.stats .lbl{font-size:11px;color:#94a3b8;margin-top:4px}.bar-wrap{width:100%;max-width:500px;margin-bottom:28px}.bar-hdr{display:flex;justify-content:space-between;font-size:12px;color:#94a3b8;margin-bottom:6px}.bar{height:10px;background:rgba(255,255,255,.08);border-radius:99px;overflow:hidden}.bar-fill{height:100%;width:{{progress||72}}%;background:linear-gradient(90deg,{{accent_color||#f59e0b}},#f97316);border-radius:99px;transition:width 1s}.cta{background:linear-gradient(135deg,{{accent_color||#f59e0b}},#f97316);color:#000;border:none;padding:18px 52px;font-size:17px;font-weight:800;border-radius:14px;cursor:pointer;box-shadow:0 8px 32px rgba(245,158,11,.35)}.disclaimer{margin-top:16px;font-size:11px;color:#475569;text-align:center;max-width:400px}</style></head><body><div class="badge"><div class="dot"></div>{{badge||PRESALE LIVE}}</div><h1>{{headline||Buy}} <span>{{token_name||$TOKEN}}</span><br>{{headline2||Before Price Goes Up}}</h1><div class="stats"><div><div class="val">{{raised||$2.4M}}</div><div class="lbl">RAISED</div></div><div><div class="val">{{holders||14,832}}</div><div class="lbl">HOLDERS</div></div><div><div class="val">{{price||$0.024}}</div><div class="lbl">CURRENT PRICE</div></div></div><div class="bar-wrap"><div class="bar-hdr><span>{{progress||72}}% Sold</span><span>{{hard_cap||$3.5M}} Hard Cap</span></div><div class="bar"><div class="bar-fill"></div></div></div><button class="cta" onclick="window.open(\"{{offer_url||#}}\",\"_blank\")">{{cta_text||CONNECT WALLET & BUY}}</button><p class="disclaimer">{{disclaimer||Cryptocurrency investments are volatile. Only invest what you can afford to lose.}}</p></body></html>',
  '[{"key":"headline","label":"Headline","type":"text","default":"Buy"},{"key":"token_name","label":"Token Name","type":"text","default":"$TOKEN"},{"key":"headline2","label":"Subheadline","type":"text","default":"Before Price Goes Up"},{"key":"badge","label":"Badge Text","type":"text","default":"PRESALE LIVE"},{"key":"raised","label":"Amount Raised","type":"text","default":"$2.4M"},{"key":"holders","label":"Holder Count","type":"text","default":"14,832"},{"key":"price","label":"Token Price","type":"text","default":"$0.024"},{"key":"progress","label":"Progress %","type":"number","default":"72"},{"key":"hard_cap","label":"Hard Cap","type":"text","default":"$3.5M"},{"key":"cta_text","label":"Button Text","type":"text","default":"CONNECT WALLET & BUY"},{"key":"offer_url","label":"Offer URL","type":"text","required":true},{"key":"bg_color","label":"Background","type":"color","default":"#0f0524"},{"key":"accent_color","label":"Accent","type":"color","default":"#f59e0b"},{"key":"disclaimer","label":"Disclaimer","type":"textarea","default":"Cryptocurrency investments are volatile. Only invest what you can afford to lose."}]',
  3.5, 1),

-- 5. Lead Gen
('Lead Capture', 'leadgen', 'Minimal lead capture form with social proof', '<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>*{margin:0;padding:0;box-sizing:border-box}body{font-family:system-ui,sans-serif;background:{{bg_color||#090a0f}};color:#fff;min-height:100vh;display:flex;align-items:center;justify-content:center;padding:20px}.card{max-width:480px;width:100%;background:rgba(22,27,34,.85);border:1px solid rgba(255,255,255,.08);border-radius:20px;padding:40px 32px;backdrop-filter:blur(12px)}.badge{display:inline-flex;align-items:center;gap:6px;background:rgba(99,102,241,.1);border:1px solid rgba(99,102,241,.2);padding:4px 12px;border-radius:20px;font-size:11px;color:{{accent_color||#6366f1}};font-weight:600;margin-bottom:20px}h1{font-size:28px;font-weight:800;line-height:1.3;margin-bottom:8px}.sub{color:#94a3b8;margin-bottom:28px;line-height:1.6;font-size:14px}input{width:100%;padding:14px 16px;background:rgba(255,255,255,.05);border:1px solid rgba(255,255,255,.1);border-radius:12px;color:#fff;font-size:14px;margin-bottom:12px;outline:none}input:focus{border-color:{{accent_color||#6366f1}}}.cta{width:100%;padding:16px;background:linear-gradient(135deg,{{accent_color||#6366f1}},{{accent2_color||#8b5cf6}});color:#fff;border:none;font-size:15px;font-weight:700;border-radius:12px;cursor:pointer;margin-bottom:16px}.social{display:flex;align-items:center;gap:8px;margin-top:20px}.avatars{display:flex}.avatars span{width:28px;height:28px;border-radius:50%;background:#334155;border:2px solid {{bg_color||#090a0f}};margin-left:-8px;display:block;font-size:10px;line-height:24px;text-align:center}.avatars span:first-child{margin-left:0}.social-text{font-size:12px;color:#94a3b8}.terms{font-size:11px;color:#475569;text-align:center;margin-top:16px}</style></head><body><div class="card"><div class="badge">{{badge||🎁 FREE GUIDE}}</div><h1>{{headline||Get Your Free Guide Today}}</h1><p class="sub">{{description||Enter your email and we will send you the complete guide instantly. No spam, ever.}}</p><input type="email" placeholder="your@email.com"><input type="text" placeholder="Your Name"><button class="cta" onclick="window.open(\"{{offer_url||#}}\",\"_blank\")">{{cta_text||SEND ME THE GUIDE}}</button><div class="social"><div class="avatars"><span>👤</span><span>👤</span><span>👤</span><span>👤</span></div><div class="social-text">{{social_proof||Join 12,400+ subscribers}}</div></div><p class="terms">We respect your privacy. Unsubscribe anytime.</p></div></body></html>',
  '[{"key":"headline","label":"Headline","type":"text","default":"Get Your Free Guide Today"},{"key":"description","label":"Description","type":"textarea","default":"Enter your email and we will send you the complete guide instantly. No spam, ever."},{"key":"badge","label":"Badge","type":"text","default":"🎁 FREE GUIDE"},{"key":"cta_text","label":"Button Text","type":"text","default":"SEND ME THE GUIDE"},{"key":"offer_url","label":"Offer URL","type":"text","required":true},{"key":"social_proof","label":"Social Proof","type":"text","default":"Join 12,400+ subscribers"},{"key":"bg_color","label":"Background","type":"color","default":"#090a0f"},{"key":"accent_color","label":"Accent","type":"color","default":"#6366f1"},{"key":"accent2_color","label":"Accent 2","type":"color","default":"#8b5cf6"}]',
  5.1, 1),

-- 6. Finance
('Forex/Course', 'finance', 'Professional financial course landing page', '<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>*{margin:0;padding:0;box-sizing:border-box}body{font-family:system-ui,sans-serif;background:{{bg_color||#090a0f}};color:#fff;min-height:100vh;padding:60px 20px;display:flex;flex-direction:column;align-items:center}.hero{text-align:center;max-width:700px}.tag{background:rgba(16,185,129,.12);border:1px solid rgba(16,185,129,.2);color:#10b981;padding:4px 14px;border-radius:20px;font-size:12px;font-weight:600;display:inline-block;margin-bottom:16px}h1{font-size:clamp(28px,5vw,46px);font-weight:800;line-height:1.2;margin-bottom:12px}h1 em{font-style:normal;color:{{accent_color||#10b981}}}.sub{color:#94a3b8;font-size:16px;line-height:1.7;max-width:520px;margin:0 auto 28px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:16px;max-width:600px;margin:0 auto 32px;width:100%}.grid div{background:rgba(255,255,255,.04);border:1px solid rgba(255,255,255,.06);border-radius:14px;padding:20px;text-align:center}.grid .icon{font-size:28px;margin-bottom:8px}.grid .txt{font-size:13px;color:#94a3b8}.cta{background:{{accent_color||#10b981}};color:#000;border:none;padding:18px 52px;font-size:17px;font-weight:700;border-radius:12px;cursor:pointer;box-shadow:0 8px 32px rgba(16,185,129,.3)}.cta:hover{transform:translateY(-2px)}.note{margin-top:16px;font-size:11px;color:#475569}</style></head><body><div class="hero"><div class="tag">{{badge||📈 ENROLLMENT OPEN}}</div><h1>{{headline||Learn to}} <em>{{headline2||Trade Profitably}}</em></h1><p class="sub">{{description||The exact strategy used by 6-figure traders. Step-by-step video course with live mentorship.}}</p><div class="grid"><div><div class="icon">📊</div><div class="txt">50+ Lessons</div></div><div><div class="icon">🎙️</div><div class="txt">Live Sessions</div></div><div><div class="icon">📱</div><div class="txt">Mobile Access</div></div><div><div class="icon">🏆</div><div class="txt">Certificate</div></div></div><button class="cta" onclick="window.open(\"{{offer_url||#}}\",\"_blank\")">{{cta_text||ENROLL NOW — $97}}</button><p class="note">{{note||30-day money-back guarantee}}</p></div></body></html>',
  '[{"key":"headline","label":"Headline","type":"text","default":"Learn to"},{"key":"headline2","label":"Highlight","type":"text","default":"Trade Profitably"},{"key":"description","label":"Description","type":"textarea","default":"The exact strategy used by 6-figure traders. Step-by-step video course with live mentorship."},{"key":"badge","label":"Badge","type":"text","default":"📈 ENROLLMENT OPEN"},{"key":"cta_text","label":"Button Text","type":"text","default":"ENROLL NOW — $97"},{"key":"offer_url","label":"Offer URL","type":"text","required":true},{"key":"bg_color","label":"Background","type":"color","default":"#090a0f"},{"key":"accent_color","label":"Accent","type":"color","default":"#10b981"},{"key":"note","label":"Note","type":"text","default":"30-day money-back guarantee"}]',
  4.0, 1);
